show_downloads: true
remote_theme: logzinga/cayman

github:
  zip_url: https://github.com/logzinga/HatRunner2/releases/download/v0.4/v0.4-Windows.zip
  tar_url: https://github.com/logzinga/HatRunner2/releases/download/v0.4/v0.4-Linux.zip
