show_downloads: true
theme: jekyll-theme-cayman

      {% if site.show_downloads %}
        <a href="{{ site.github.zip_url }}" class="btn">Download Windows</a>
        <a href="{{ site.github.tar_url }}" class="btn">Download Linux</a>
      {% endif %}

github:
  zip_url: https://github.com/logzinga/HatRunner2/releases/download/v0.4/v0.4-Windows.zip
  tar_url: https://github.com/logzinga/HatRunner2/releases/download/v0.4/v0.4-Linux.zip
