show_downloads: true
download_android: false
remote_theme: logzinga/cayman-hatrunner2

github:
  zip_url: https://github.com/logzinga/HatRunner2/releases/download/v1.0/v1.0-Windows.zip
  tar_url: https://github.com/logzinga/HatRunner2/releases/download/v1.0/v1.0-Linux.tar.gz
